@baseUrl = http://localhost:3333

@authToken = {{authenticate.response.body.access_token}}


###

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "firstName": "branchieri",
    "lastName": "ADMIN",
    "email": "branchi@dev.com",
    "password": "123123123",
    "image": "",
    "phone": "54999999999",
    "adress": "Rua antares 857",
    "cep": "95076540",
    "role": "ADMIN"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "branchieri@admin.com",
    "password": "123123123"
}

###

# @name edit_user
POST {{baseUrl}}/accounts/edit/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{   
    "firstName": "Guilherme",
	"lastName": "Branchieri",
	"image": "https://gnosisbrasil.com/storage/2015/09/aleph.png",
	"phone": "54991053056",
	"adress": "Rua Manoel de Abreu 716",
	"cep": "95074280"
}

###

# @name create_product
POST {{baseUrl}}/products/create/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{   
    "name": "Difusor de teste 12",
    "price": 4.50,
    "description": "Lindo difusor pra testar essa funcionalidade de criação",
    "images": ["wwww.minha-imagem.com"],
    "available": true,
    "category": "casamento"
}

###

# @name edit_product
POST {{baseUrl}}/products/edit/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{   
    "data": {
        "id": "product01",
        "name": "vela",
        "price": 8.00,
        "description": "Linda vela",
        "images": ["wwww.minha-imagem.com"],
        "available": false,
        "category": "batizado"
    }
}

###

# @name delete_product
POST {{baseUrl}}/products/delete/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{   
    "id": "product01"
}

###

# @name find_all_product

GET {{baseUrl}}/products/list
Content-Type: application/json


